uservice/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.login_page, name='login'),
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('logout/', views.logout_page, name='logout'),
    path('gallery', views.gallery, name='gallery'),
    path('photo/<str:pk>/', views.viewPhoto, name='photo'),
    path('add/', views.addPhoto, name='add'),
]

uservice/uservice/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

uservice/account/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class Photo(models.Model):
    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photos'

    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(null=False, blank=False)
    description = models.TextField()

    def __str__(self):
        return self.description


class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    photo = models.ForeignKey(Photo, on_delete=models.Case, null=True, blank=True)
    text = models.CharField(max_length=225)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

uservice/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, TextInput
from .models import Post


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text']
        widgets = {
            'text': TextInput(attrs={'class': 'input', 'placeholder': 'Say something...'})
        }

uservice/account/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .models import Category, Photo, Post
from django.contrib.auth.decorators import login_required
from nltk.sentiment import SentimentIntensityAnalyzer

from .forms import CreateUserForm, PostForm


def register_page(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy('account:gallery'))
    else:
        form = CreateUserForm()
        success_url = reverse_lazy('account:login')
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)
                return HttpResponseRedirect(success_url)

        context = {'form': form}
        return render(request, 'register.html', context)


def login_page(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy('account:gallery'))
    else:
        success_url = reverse_lazy('account:gallery')
        failure_url = reverse_lazy('account:login')
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(success_url)
            else:
                messages.info(request, 'Username or password is incorrect')
                return HttpResponseRedirect(failure_url)
        context = {}
        return render(request, 'login.html', context)


def logout_page(request):
    success_url = reverse_lazy('account:login')
    logout(request)
    return HttpResponseRedirect(success_url)


@login_required(login_url='account:login')
def gallery(request):
    user = request.user
    category = request.GET.get('category')
    if category == None:
        photos = Photo.objects.all()
    else:
        photos = Photo.objects.filter(
            category__name=category, category__user=user)
    photo_scores = {}
    for photo in photos:
        posts = Post.objects.filter(photo=photo).order_by('-date_posted').all()
        sia = SentimentIntensityAnalyzer()
        scores = {'negative': 0, 'positive': 0, 'neutral': 0}
        for post in posts:
            score = sia.polarity_scores(str(post))
            maximum = max(score['neg'], score['neu'], score['pos'])
            if maximum == score['neg']:
                scores['negative'] += 1
            if maximum == score['neu']:
                scores['neutral'] += 1
            if maximum == score['pos']:
                scores['positive'] += 1
        if photo.id not in photo_scores.keys():
            photo_scores[photo.id] = scores
    categories = Category.objects.filter(user=user)
    context = {'categories': categories, 'photos': photos, 'scores': photo_scores}
    return render(request, 'gallery.html', context)


@login_required(login_url='account:login')
def viewPhoto(request, pk):
    photo = Photo.objects.get(id=pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.photo = photo
            post.save()
            return HttpResponseRedirect(request.path_info)
    else:
        form = PostForm()
    posts = Post.objects.filter(photo=photo).order_by('-date_posted').all()
    sia = SentimentIntensityAnalyzer()
    post_score = {}
    for post in posts:
        score = sia.polarity_scores(str(post))
        maximum = max(score['neg'], score['neu'], score['pos'])
        if maximum == score['neg']:
            post_score[post.id] = -1
        if maximum == score['neu']:
            post_score[post.id] = 0
        if maximum == score['pos']:
            post_score[post.id] = 1
    context = {'form': form, 'posts': posts, 'photo': photo, 'post_score': post_score}
    return render(request, 'photo.html', context)


@login_required(login_url='login')
def addPhoto(request):
    user = request.user

    categories = user.category_set.all()

    if request.method == 'POST':
        data = request.POST
        images = request.FILES.getlist('images')

        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(
                user=user,
                name=data['category_new'])
        else:
            category = None

        for image in images:
            photo = Photo.objects.create(
                category=category,
                description=data['description'],
                image=image,
            )

        return redirect('account:gallery')

    context = {'categories': categories}
    return render(request, 'add.html', context)

uservice/account/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>login</title>
    <link rel="shortcut icon" href="#">
    <link href="{% static 'css/bootstrap_css.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="frame">
        <div class="nav">
            <h2 style="text-align: center; color: whitesmoke">Existing User</h2>
        </div>
        <form action="" method="post" style="padding:30px">
            {% csrf_token %}
            <label for="username">username</label>
            <input class="form-styling" style="color: white" type="text" id="username" placeholder="" name="username"/>
            <label for="password_toggle">Password</label>
            <input class="form-styling" style="color: white" type="password" id="password_toggle" placeholder=""
                   name="password"/>


            <input type="checkbox" onclick="myFunction()" id="showpass"/>
            <label for="showpass">Show</label>

            <input class="btn btn-animate" type="submit" value="Login to your account"/>
            <div>&nbsp;</div>

        </form>
        {% for message in messages %}
            <p id="messages" style="text-align: center;">{{ message }}</p>
        {% endfor %}

        <div style="text-align: center;color: white">Don't have an account?<a href="{% url 'account:register' %}"
                                                                  type="link"><strong>Sign Up</strong></a></div>

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap_js.js' %}"></script>
</body>
</html>

uservice/account/templates/photos/add.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Add Photo</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link href="{% static 'css/bootstrap_css.css' %}" rel="stylesheet">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>

<body class="m-5">
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-4">
                <a href="{% url 'account:gallery' %}" class="btn btn-dark my-3">Go Back</a>
                <div class="card">


                    <form method='POST' action="" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group m-3">
                            <label>Description</label>
                            <input required name="description" type="text" placeholder="Enter a description"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Select a category</label>
                            <select name="category" class="form-control">
                                <option value='none'>Select a category...</option>

                                {% for category in categories %}
                                <option value='{{category.id}}'>{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>


                        <div class="form-group m-3">
                            <label>Create a new category</label>
                            <input name="category_new" type="text" placeholder="Create a new category"
                                class="form-control">
                        </div>

                        <div class="form-group m-3">
                            <label>Upload image</label>
                            <input required name="images" type="file" multiple class="form-control-file">
                        </div>

                        <button type='submit' class="btn btn-dark m-3">Submit</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

uservice/account/templates/photos/gallery.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gallery</title>
    <link href="{% static 'css/bootstrap_css.css' %}" rel="stylesheet">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <style>
        .image-thumbail {
            height: 200px;
            object-fit: cover;
        }

        .list-group-item a {
            text-decoration: none;
            color: black;
        }
    </style>
</head>

<body class="m-5">

    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {% if request.user.is_authenticated %}
                <h3 style="text-align: center">Hello {{request.user}}</h3>
                {% endif %}
                <div class="card">
                    <div class="card-header">
                        Categories
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'account:gallery' %}">All</a>
                        </li>
                        {% for category in categories %}
                        <li class=" list-group-item">
                            <a href="{% url 'account:gallery' %}?category={{category.name}}">
                                {{category.name}}
                            </a>
                        </li>
                        {% endfor %}


                        <a href="{% url 'account:add' %}" class="btn btn-dark btn-block btn-sm m-1">Add Photo</a>
                        <a href="{% url 'account:logout' %}" class="btn btn-dark btn-block btn-sm m-1">Logout</a>
                    </ul>
                </div>

            </div>
            <div class="col-md-9">
                <div class="row">

                    {% for photo in photos %}
                    <div class="col-md-4">
                        <div class="card my-2">
                            <img class="image-thumbail hover-shadow" src="{{photo.image.url}}" alt="Card image cap" onclick="window.location.href='{% url 'account:photo' photo.id %}';">

                            <div class="card-body">
                                <small>Category: {{photo.category.name}}</small>
                                {% for photo_score, value in scores.items %}
                                    {% if photo_score == photo.id %}
                                        <p style="display: inline">🙂</p> {{value.positive}}
                                        <p style="display: inline">&#128533;</p> {{value.negative}}
                                        <p style="display: inline">😐</p> {{value.neutral}}
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <a href="{% url 'account:photo' photo.id %}" class="btn btn-outline-dark btn-sm m-1">View</a>
                        </div>
                    </div>
                    {% empty %}
                    <h3>No photos...</h3>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>

</body>

</html>

uservice/account/templates/photos/photo.html
{% load humanize %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Photo</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <meta charset="UTF-8">
    <link href="{% static 'css/bootstrap_css.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>

<body class="m-5">
<div class="container">
    <div class="row justify-content-center">
        <div class="row">
            <div class="col-sm-2">
                <a href="{% url 'account:gallery' %}" class="btn btn-dark my-3">Go Back</a>
            </div>

            <div class='col-sm-5' style="height: 90vh;">
                <img style="max-width: 100%; max-height: 100%;" src="{{photo.image.url}}">

                <p>{{photo.description}}</p>


            </div>
            <div class="col-sm-4 ">
                <div class="col">

                    <div class=" ScrollStyle">
                        {% if posts %}
                        {% for post in posts %}
                        <article class="media mt-5">
                            <div class="media-content">
                                <div class="content">
                                    {% for key, value in post_score.items %}
                                        {% if key == post.id %}
                                        {% if value == 1 %}
                                            <p class="positive">
                                                <strong>{{ post.user.username }}</strong>
                                                <small>{{ post.date_posted|naturaltime }}</small>
                                                <br>
                                                {{ post.text }}
                                            </p>
                                        {% elif value == 0 %}
                                        <p class="neutral">
                                                <strong>{{ post.user.username }}</strong>
                                                <small>{{ post.date_posted|naturaltime }}</small>
                                                <br>
                                                {{ post.text }}
                                            </p>
                                        {% elif value == -1 %}
                                        <p class="negative">
                                                <strong>{{ post.user.username }}</strong>
                                                <small>{{ post.date_posted|naturaltime }}</small>
                                                <br>
                                                {{ post.text }}
                                            </p>
                                        {% else %}
                                            <p>
                                                <strong>{{ post.user.username }}</strong>
                                                <small>{{ post.date_posted|naturaltime }}</small>
                                                <br>
                                                {{ post.text }}
                                            </p>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}

                                </div>
                            </div>

                        </article>
                        {% endfor %}
                        {% else %}
                        <article class="media">
                            <div class="media-content">
                                <div class="content has-text-centered">
                                    <p>There are no posts.</p>
                                </div>
                            </div>
                        </article>
                        {% endif %}
                    </div>
                    <div>
                        <form method="POST">
                            <article class="media">
                                <div class="media-content">
                                    <div class="field">
                                        <p class="control">
                                            {% csrf_token %}
                                        <div class="field has-addons ">
                                            <div class="control is-expanded">
                                                <input class="form-styling" type="text" id="comment"
                                                       placeholder="Say something..." name="text"/>
                                            </div>
                                            <div class="control">
                                                <button class="button is-info btn btn-dark">Submit</button>
                                            </div>
                                        </div>
                                        </p>
                                    </div>
                                </div>
                            </article>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>

</html>

uservice/account/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
    <link rel="shortcut icon" href="#">
    <link href="{% static 'css/bootstrap_css.css' %}" rel="stylesheet">

</head>
<body>
<div class="container">
    <div class="frame">
        <div class="nav">
            <h2 style="text-align: center; color: whitesmoke">New User</h2>
        </div>
        <form action="" method="post" style="padding: 30px;">
            {% csrf_token %}
            <label for="username">{{ form.username.label }}</label>
            <input class="form-styling" style="color: white" placeholder="" type="text" id="username" name="{{ form.username.name }}"
                   value="{{ form.username.value|default_if_none:'' }}"/>
            <label for="email">{{ form.email.label }}</label>
            <input class="form-styling" style="color: white" type="email" id="email" placeholder="" name="{{ form.email.name }}"
                   value="{{ form.email.value|default_if_none:'' }}"/>
            <label for="password1">{{ form.password1.label }}</label>
            <input class="form-styling" style="color: white" type="password" id="password1" placeholder="" name="{{ form.password1.name }}"
                   value="{{ form.password1.value|default_if_none:'' }}"/>
            <label for="password2">{{ form.password2.label }}</label>
            <input class="form-styling" style="color: white" type="password" id="password2" placeholder="" name="{{ form.password2.name }}"
                   value="{{ form.password2.value|default_if_none:'' }}"/>
            <input class="btn btn-animate" type="submit" name="Create User" value="Create User"/>
            <div>&nbsp;</div>
        </form>

        <div style="text-align: center;color: white">Already have an account?<a href="{% url 'account:login' %}"
                                                                    type="link"><strong>Login</strong></a>
        </div>

        <div style="text-align: center;">
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% endif %}
        </div>

    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap_js.js' %}"></script>
</body>
</html>